language: node_js
node_js:
  - "6.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
services:
  - mongodb
  - redis-server

env:
  - NODE_ENV=travis
  - MONGO_URL=mongodb://localhost:27017/accounts_test
  - REDIS_HOST=localhost
  - REDIS_PORT=6379
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

after_success:
  "npm run deploy"
