language: node_js
node_js:
  - "6.1"

sudo: required

services:
  - mongodb
  - redis-server

env:
  - NODE_ENV=travis MONGO_URL=mongodb://localhost:27017/accounts_test REDIS_HOST=localhost REDIS_PORT=6379

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

after_success:
  "npm run deploy"
